name: "CI"

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:
    inputs:
      workflow:
        description: "Workflow to run"
        required: true
        default: "lint"

jobs:

  lint:
    uses: "./.github/workflows/lint.yaml"

  test:
    uses: "./.github/workflows/test.yaml"

  build:
    needs:
      - lint
      - test
    uses: "./.github/workflows/build.yaml"
