name: "Publish 🚀"

on:
  push:
    tags:
      - "v*"

jobs:
  lint:
    uses: "./.github/workflows/lint.yaml"

  build:
    uses: "./.github/workflows/build.yaml"

  github-release:
    name: "GitHub Release"
    runs-on: ubuntu-latest
    needs:
      - lint
      - build
    steps:
      - name: "Release 🚀"
        uses: "softprops/action-gh-release@v1"
        with:
          generate_release_notes: true

  publish-npm:
    name: "Publish to NPM"
    needs:
      -  github-release
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: astro-posthog
          path: ./dist
          
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: "https://registry.npmjs.org/"

      - uses: pnpm/action-setup@v2
        with:
          run_install: false

        # --no-git-checks is needed, because this pipelies runs on the pushed tag which is in a detached HEAD state
      - run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
